//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECURETEST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SECURESOFT : DbContext
    {
        public SECURESOFT()
            : base("name=SECURESOFT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SALE> SALEs { get; set; }
        public virtual DbSet<SALE_REPO> SALE_REPO { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
    }
}
